### PR TITLE
CouchRest.configure block for setting connection options.

### PR DESCRIPTION
**Pull request by oivoodoo**
- [ ] fix `An error occurred while installing mime-types-data (3.2016.0221), and Bundler` for `jruby`

### CODE REVIEW

**Comment by joelnb** [comment]
Would you mind having a look at https://github.com/couchrest/couchrest/pull/116 as we seem to be aiming to fix some of the same issues?

**Comment by oivoodoo** [comment]
@joelnb yes, I have already seen this pull request. but it's a bit different approach. I don't know is it good fit for your library or not. But in my version you can globally for CouchRest define configuration in initialize block for example. As result you don't need to make fat constructor for `CouchRest::Server` to support different kind of the options to pass there.

**Comment by joelnb** [comment]
I'm not the maintainer so we'll have to see what @samlown thinks about it. 

I find my way simpler for what I need to do but it looks like I could do everything I need to using your way of doing things as well. The only misgiving I have about your approach is that it looks like it would be trickier to have, for example, 2 couchrest server instances with different configurations because the config exists at the module level rather than being passed to the constructor. I could be wrong about that though as I haven't yet had time to test your branch.

**Comment by oivoodoo** [comment]
@joelnb I can propose the changes like that:

```ruby

CouchRest.configure("staging") do |config|
  config.server_url = "http://staging"
end

CouchRest.configure("production") do |config|
  config.server_url = "http://production"
end

CouchRest.configure do |config|
  config.server_url = "http://global"
end

server1 = CouchRest.new("staging")
server2 = CouchRest.new("production")
server3 = CouchRest.new

but it should be still possible to pass server url and other options. But it sounds like more complex for understading.
```

**Comment by samlown** [comment]
Not super-convinced about this... for more sophisticated configuration options, I'd suggest using CouchRest Model, which acheives the same.

**Comment by oivoodoo** [comment]
going to close it, no sense to keep it for years :)

**Pull request closed without merging**
